COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
UNICODEMAP_ENABLE = no 
RAW_ENABLE = yes
CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
KEYSTATS_ENABLE = yes

SRC += hid.c
SRC += key_overrides.c
